image: Visual Studio 2019

skip_commits:
  files:
  - BUILDING.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - LICENSE
  - README.md
  
version: 1.0.{build}

branches:
  only:
  - master

platform: Any CPU

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: EF.Tests.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:administrator -target:".\xunit.console.x86.exe" -targetargs:"C:\projects\entityframework-codefirst\UnitTests\bin\Debug\netcoreapp3.1\UnitTests.dll" -output:".\MyProject_coverage.xml"

#upload report
- codecov -f ".\MyProject_coverage.xml"

