image: Visual Studio 2019

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov
- choco install xunit

build:
  project: EF.Tests.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:administrator -target:".\xunit.console.exe" -targetargs:"UnitTests\bin\Debug\netcoreapp3.1\UnitTests.dll" -output:".\MyProject_coverage.xml"

#upload report
- codecov -f "MyProject_coverage.xml"

