image: Visual Studio 2019

skip_commits:
  files:
  - BUILDING.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - LICENSE
  - README.md
  
before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov
- choco install xunit

build:
  project: EF.Tests.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:administrator -target:".\xunit.console.x86.exe" -targetargs:".\UnitTests\bin\Debug\netcoreapp3.1\UnitTests.dll -noshadow" -output:".\MyProject_coverage.xml"

#upload report
- codecov -f "MyProject_coverage.xml"

